'use strict';

const fs = require('fs');
const path = require('path');
const { TARGETS, abs } = require('./paths');
const { withEol } = require('./eol');

function patchNames(id) {
  return {
    generate: `${id}--generate.js`,
    promo: `${id}--paste-into-thrive-special-offer-promo.html`,
    builder: `${id}--paste-into-thrive-special-offer-builder.html`,
    banner: `${id}--paste-into-thrive-homepage-banner.html`,
    button: `${id}--paste-into-wpcode-global-special-offer-button.html`,
    preview: `${id}--preview.html`,
    yoast: `${id}--yoast.md`,
  };
}

function generateJs(id) {
  return `#!/usr/bin/env node
'use strict';
const path = require('path');
const { writePatchDir, readManifestFromState } = require('../../scripts/campaign/patches');
const repoRoot = path.resolve(__dirname, '..', '..');
const manifest = readManifestFromState(repoRoot);
if (!manifest || manifest.id !== ${JSON.stringify(id)}) {
  throw new Error('State manifest id does not match this patch directory (${id}).');
}
const render = require('../../scripts/campaign/render');
writePatchDir(repoRoot, manifest, {
  promo: render.renderPromo(manifest),
  builder: render.renderBuilderElement(manifest),
  banner: render.renderBanner(manifest),
  button: render.renderButton(manifest),
  preview: render.renderPreview(manifest),
  yoast: render.renderYoast(manifest),
});
console.log('[campaign] regenerated artifacts for ${id}');
`;
}

function readmeFor(manifest) {
  const id = manifest.id;
  const parked = manifest.status === 'parked';
  return `# ${id}

Prepared paste artifacts from \`scripts/campaign\`.
Campaign status: **${manifest.status}**.
Offer tag: \`${manifest.offerTag}\`.

This directory is regenerated by the campaign engine. Do not hand-edit paste files.

## 🛑 HUMAN GATE — live pastes

Nothing here is live until a human pastes it. Never paste a whole repo page file into Thrive.

### 1. \`/special-offer/\` promo (Thrive Custom HTML)

File: \`${id}--paste-into-thrive-special-offer-promo.html\`

Replace the existing campaign promo element below the video hero. Select-all in the Thrive code box.

### 2. \`/special-offer/\` membership builder JS (Thrive Custom HTML)

File: \`${id}--paste-into-thrive-special-offer-builder.html\`

Replace the inlined builder element (\`data-css="tve-u-693b313a87da28"\`). Do **not** also enable WPCode #7966 on this page.

### 3. Homepage campaign banner (Thrive Custom HTML)

File: \`${id}--paste-into-thrive-homepage-banner.html\`

Paste as one Custom HTML block on \`/\`. Remove any previous seasonal offer banner/hero CTA.

### 4. Global floating offer button (WPCode HTML snippet, footer)

File: \`${id}--paste-into-wpcode-global-special-offer-button.html\`

${parked
    ? 'Disable the snippet. Parking hides the button in JS; disabling it is the real off switch.'
    : `Create the snippet on first use (HTML, site-wide, footer). Record the assigned ID and mirror the **editor** contents to \`live/wpcode/<id>-global-special-offer-button.html\` in the same session. Later campaigns replace this one snippet — do not create a second.`}

Confirm the save by the **"Snippet updated."** notice.

### 5. Yoast

See \`${id}--yoast.md\`. Page HTML meta tags do not affect Google.

### 6. Cache and curl

Flush GoDaddy cache, then verify with curl, not the browser.

\`\`\`powershell
curl.exe -sL "https://southendclub.com/special-offer/?nocache=$([DateTimeOffset]::Now.ToUnixTimeSeconds())" -o "$env:TEMP\\se-offer.html"
Select-String -Path "$env:TEMP\\se-offer.html" -Pattern "se-campaign-promo","${manifest.offerTag}" | Measure-Object | Select-Object -ExpandProperty Count
\`\`\`

Expect a non-zero count for \`se-campaign-promo\`. Expect the offer tag **${manifest.offerTag}**. Expect **0** hits for the previous campaign tag.

\`\`\`powershell
curl.exe -sL "https://southendclub.com/?nocache=$([DateTimeOffset]::Now.ToUnixTimeSeconds())" | Select-String "se-campaign-float","se-campaign-banner"
\`\`\`

Expect the banner on the homepage. Expect **one** \`se-campaign-float\` on ordinary pages and **zero** visible copies on \`/special-offer/\` (the markup may be present globally; the script must not add \`is-visible\` there).

## Regenerate

\`\`\`powershell
node patches/${id}/${id}--generate.js
\`\`\`
`;
}

function readManifestFromState(repoRoot) {
  const p = abs(repoRoot, TARGETS.state);
  if (!fs.existsSync(p)) return null;
  const state = JSON.parse(fs.readFileSync(p, 'utf8'));
  return state.manifest || null;
}

function writePatchDir(repoRoot, manifest, artifacts) {
  const id = manifest.id;
  const dir = abs(repoRoot, path.join(TARGETS.patchesDir, id));
  fs.mkdirSync(dir, { recursive: true });
  const names = patchNames(id);
  const lf = (s) => withEol(String(s).replace(/\r\n/g, '\n').replace(/\n$/, '') + '\n', '\n');
  fs.writeFileSync(path.join(dir, 'README.md'), lf(readmeFor(manifest)));
  fs.writeFileSync(path.join(dir, names.generate), lf(generateJs(id)));
  fs.writeFileSync(path.join(dir, names.promo), lf(artifacts.promo));
  fs.writeFileSync(path.join(dir, names.builder), lf(artifacts.builder));
  fs.writeFileSync(path.join(dir, names.banner), lf(artifacts.banner));
  fs.writeFileSync(path.join(dir, names.button), lf(artifacts.button));
  fs.writeFileSync(path.join(dir, names.preview), lf(artifacts.preview));
  fs.writeFileSync(path.join(dir, names.yoast), lf(artifacts.yoast));
  return dir;
}

module.exports = { patchNames, writePatchDir, readManifestFromState, readmeFor };
