'use strict';

const fs = require('fs');
const path = require('path');
const { escapeHtml, headlineHtml } = require('./html');
const { endLabelNbsp } = require('./dates');
const { PARKED } = require('./manifest');

const TONES = {
  urgency: { fabEmoji: '⏳' },
  family: { fabEmoji: '☀️' },
  'lock-in': { fabEmoji: '🔒' },
};

function toneOf(manifest) {
  return TONES[manifest.tone] || TONES.urgency;
}

function duesMap(manifest) {
  const d = manifest.duesDiscount || {};
  return {
    single: Number(d.single) || 0,
    couple: Number(d.couple) || 0,
    family: Number(d.family) || 0,
  };
}

function hasDuesDiscount(manifest) {
  const d = duesMap(manifest);
  return d.single > 0 || d.couple > 0 || d.family > 0;
}

function perkItems(manifest) {
  if (manifest.status === 'parked') return ['OFFER NOT SET'];
  const items = [];
  if (manifest.enrollment) items.push(`<strong>$${manifest.enrollment}</strong> enrollment`);
  if (hasDuesDiscount(manifest)) {
    const d = duesMap(manifest);
    if (d.single === d.couple && d.couple === d.family) {
      items.push(`<strong>$${d.single}</strong> off monthly dues`);
    } else {
      items.push(`<strong>$${d.single}</strong> / <strong>$${d.couple}</strong> / <strong>$${d.family}</strong> off monthly dues`);
    }
  }
  if (manifest.guestPasses) items.push(`<strong>${manifest.guestPasses}</strong> guest passes`);
  if (manifest.endParts) {
    items.push(`Ends <strong>${endLabelNbsp(manifest.endParts.year, manifest.endParts.month, manifest.endParts.day)}</strong>`);
  }
  return items.length ? items : (manifest.perks || []).map(escapeHtml);
}

function endExpr(manifest) {
  return manifest.endDateISO ? `new Date('${manifest.endDateISO}')` : 'null';
}

function countdownScriptFromUnits(manifest, units) {
  const map = Object.keys(units)
    .map((id) => `'${id}': pad(${units[id]})`)
    .join(', ');
  return `(function () {
  var END = ${endExpr(manifest)};
  function pad(n) { return n < 10 ? '0' + n : '' + n; }
  function tick() {
    var now = new Date();
    if (!END) { return; }
    var diff = Math.max(0, END - now);
    var s = Math.floor(diff / 1000);
    var d = Math.floor(s / 86400); s %= 86400;
    var h = Math.floor(s / 3600); s %= 3600;
    var m = Math.floor(s / 60); s %= 60;
    var map = { ${map} };
    Object.keys(map).forEach(function (id) {
      var el = document.getElementById(id);
      if (el) el.textContent = map[id];
    });
  }
  tick();
  setInterval(tick, 1000);
})();`;
}

function renderMeta(manifest) {
  const title = escapeHtml(manifest.yoast && manifest.yoast.title ? manifest.yoast.title : `${manifest.headline} | South End Club`.replace(/\n/g, ' '));
  const desc = escapeHtml((manifest.yoast && manifest.yoast.description) || manifest.preheader || manifest.limitedTimeText || 'OFFER NOT SET.');
  const ogTitle = escapeHtml((manifest.headline || '').replace(/\n/g, ' '));
  return [
    `<title>${title}</title>`,
    `<meta name="title" content="${title}">`,
    `<meta name="description" content="${desc}">`,
    `<meta property="og:title" content="${ogTitle}">`,
    `<meta property="og:description" content="${desc}">`,
    `<meta name="twitter:title" content="${ogTitle}">`,
    `<meta name="twitter:description" content="${desc}">`,
  ].join('\n');
}

function renderCallout(manifest) {
  const eyebrow = escapeHtml(manifest.eyebrow || manifest.endLabel || 'Special offer');
  const title = headlineHtml(manifest.headline);
  const perks = perkItems(manifest)
    .map((p) => `<span>${p}</span>`)
    .join('\n        ');
  return `<div class="so-offer-callout" id="se-campaign-callout">
      <div class="so-offer-callout-eyebrow">${eyebrow}</div>
      <div class="so-offer-callout-title">${title}</div>
      <div class="so-offer-callout-perks">
        ${perks}
      </div>
    </div>`;
}

function renderPromo(manifest) {
  const t = toneOf(manifest);
  const aria = escapeHtml(manifest.eyebrow || 'Membership special');
  const perks = perkItems(manifest)
    .map((p) => `<span class="se-campaign-perk">${p}</span>`)
    .join('\n      ');
  const cta = escapeHtml(manifest.status === 'parked' ? 'OFFER NOT SET' : (manifest.primaryCta.label || 'Build Your Membership'));
  const details = manifest.status === 'parked'
    ? 'OFFER NOT SET'
    : [
        manifest.enrollment ? `$${manifest.enrollment}` : null,
        hasDuesDiscount(manifest) ? 'lower dues' : null,
        manifest.guestPasses ? `${manifest.guestPasses} passes` : null,
        manifest.endParts ? endLabelNbsp(manifest.endParts.year, manifest.endParts.month, manifest.endParts.day).replace('&nbsp;', ' ') : null,
      ].filter(Boolean).join(' · ');
  const script = countdownScriptFromUnits(manifest, {
    'se-camp-days': 'd',
    'se-camp-hours': 'h',
    'se-camp-minutes': 'm',
    'se-camp-seconds': 's',
    'se-camp-fab-days': 'd',
    'se-camp-fab-hours': 'h',
  });

  return `<!-- Campaign promo — generated by scripts/campaign. Do not hand-edit. -->
<div id="se-campaign-promo" class="se-campaign-promo" role="region" aria-label="${aria}">
  <div class="se-campaign-promo-inner">
    <div class="se-campaign-promo-tag">${escapeHtml(manifest.eyebrow || 'Special offer')}</div>
    <div class="se-campaign-promo-offer">${headlineHtml(manifest.headline)}</div>
    <div class="se-campaign-promo-perks">
      ${perks}
    </div>
    <div class="se-campaign-promo-countdown" aria-live="polite">
      <span class="se-campaign-cd"><span id="se-camp-days">00</span><small>d</small></span>
      <span class="se-campaign-cd"><span id="se-camp-hours">00</span><small>h</small></span>
      <span class="se-campaign-cd"><span id="se-camp-minutes">00</span><small>m</small></span>
      <span class="se-campaign-cd"><span id="se-camp-seconds">00</span><small>s</small></span>
    </div>
    <a class="se-campaign-promo-cta" href="#membershipBuilder">${cta}</a>
  </div>
</div>

<a href="#membershipBuilder" class="se-campaign-fab" draggable="false" aria-label="${aria}">
  <span class="se-campaign-fab-emoji" aria-hidden="true">${t.fabEmoji}</span>
  <span class="se-campaign-fab-copy">
    <span class="se-campaign-fab-label">Offer</span>
    <span class="se-campaign-fab-details">${escapeHtml(details.replace(/&nbsp;/g, ' '))}</span>
    <span class="se-campaign-fab-time"><span id="se-camp-fab-days">00</span>d <span id="se-camp-fab-hours">00</span>h left</span>
  </span>
</a>

<style>
#se-campaign-promo,
#se-campaign-promo * {
  box-sizing: border-box !important;
  -webkit-font-smoothing: antialiased !important;
}
#se-campaign-promo {
  position: relative !important;
  z-index: 2 !important;
  width: 100% !important;
  max-width: 720px !important;
  margin: 28px auto 36px !important;
  padding: 0 16px !important;
  text-align: center !important;
  font-family: Montserrat, system-ui, sans-serif !important;
}
#se-campaign-promo .se-campaign-promo-inner {
  display: flex !important;
  flex-direction: column !important;
  align-items: center !important;
  gap: 10px !important;
  margin: 0 auto !important;
  padding: 18px 20px 16px !important;
  background: linear-gradient(145deg, #0b468c, #163d6b 55%, #204147) !important;
  border: 2px solid #b8860b !important;
  border-radius: 18px !important;
  box-shadow: 0 14px 36px rgba(11,70,140,0.28), 0 0 0 1px rgba(255,255,255,0.08) inset !important;
}
#se-campaign-promo .se-campaign-promo-tag {
  display: inline-block !important;
  margin: 0 !important;
  padding: 5px 12px !important;
  color: #1a1205 !important;
  background: linear-gradient(135deg, #f0d78c, #b8860b) !important;
  font-size: 11px !important;
  font-weight: 800 !important;
  letter-spacing: 0.1em !important;
  text-transform: uppercase !important;
  border-radius: 999px !important;
  max-width: 100% !important;
  overflow-wrap: break-word !important;
}
#se-campaign-promo .se-campaign-promo-offer {
  margin: 0 !important;
  color: #ffffff !important;
  font-size: clamp(20px, 3.2vw, 26px) !important;
  font-weight: 800 !important;
  letter-spacing: -0.02em !important;
  line-height: 1.2 !important;
  text-wrap: balance !important;
  max-width: 100% !important;
  overflow-wrap: break-word !important;
}
#se-campaign-promo .se-campaign-promo-perks {
  display: flex !important;
  flex-wrap: wrap !important;
  justify-content: center !important;
  gap: 8px !important;
}
#se-campaign-promo .se-campaign-perk {
  display: inline-block !important;
  padding: 6px 12px !important;
  color: #fff !important;
  background: rgba(0,0,0,0.25) !important;
  border: 1px solid rgba(255,255,255,0.25) !important;
  border-radius: 999px !important;
  font-size: 12px !important;
  font-weight: 600 !important;
}
#se-campaign-promo .se-campaign-perk strong { color: #ffd978 !important; font-weight: 800 !important; }
#se-campaign-promo .se-campaign-promo-countdown {
  display: flex !important;
  justify-content: center !important;
  gap: 6px !important;
  font-variant-numeric: tabular-nums !important;
}
#se-campaign-promo .se-campaign-cd {
  min-width: 46px !important;
  padding: 6px 4px !important;
  background: rgba(0,0,0,0.28) !important;
  border: 1px solid rgba(255,255,255,0.16) !important;
  border-radius: 10px !important;
  color: #fff !important;
  font-size: 16px !important;
  font-weight: 800 !important;
  line-height: 1.1 !important;
}
#se-campaign-promo .se-campaign-cd small {
  display: block !important;
  margin-top: 2px !important;
  font-size: 9px !important;
  font-weight: 700 !important;
  letter-spacing: 0.08em !important;
  text-transform: uppercase !important;
  color: rgba(255,255,255,0.7) !important;
}
#se-campaign-promo .se-campaign-promo-cta {
  display: inline-flex !important;
  align-items: center !important;
  justify-content: center !important;
  min-height: 44px !important;
  margin-top: 4px !important;
  padding: 11px 22px !important;
  max-width: min(280px, calc(100vw - 64px)) !important;
  border-radius: 999px !important;
  color: #1a1205 !important;
  background: linear-gradient(135deg, #f0d78c, #b8860b) !important;
  font-size: 13px !important;
  font-weight: 800 !important;
  letter-spacing: 0.04em !important;
  text-transform: uppercase !important;
  text-decoration: none !important;
  box-shadow: 0 8px 20px rgba(184,134,11,0.4) !important;
}
.se-campaign-fab {
  position: fixed !important;
  left: 14px !important;
  top: 140px !important;
  z-index: 999 !important;
  display: inline-flex !important;
  align-items: center !important;
  gap: 8px !important;
  max-width: calc(100vw - 28px) !important;
  min-height: 44px !important;
  padding: 9px 14px 9px 10px !important;
  text-decoration: none !important;
  color: #1a1205 !important;
  background: linear-gradient(135deg, #ffe08a 0%, #f5c84b 45%, #e8a317 100%) !important;
  border: 1px solid rgba(255,255,255,0.65) !important;
  border-radius: 18px !important;
  box-shadow: 0 10px 28px rgba(232,163,23,0.45) !important;
  font-family: Montserrat, system-ui, sans-serif !important;
  line-height: 1.15 !important;
}
body.admin-bar .se-campaign-fab { top: 172px !important; }
.se-campaign-fab.is-hidden {
  opacity: 0 !important;
  visibility: hidden !important;
  pointer-events: none !important;
}
.se-campaign-fab-emoji { font-size: 20px !important; line-height: 1 !important; }
.se-campaign-fab-copy { display: flex !important; flex-direction: column !important; align-items: flex-start !important; gap: 2px !important; min-width: 0 !important; }
.se-campaign-fab-label { font-size: 10px !important; font-weight: 800 !important; letter-spacing: 0.14em !important; text-transform: uppercase !important; }
.se-campaign-fab-details { font-size: 12px !important; font-weight: 800 !important; color: #0b468c !important; }
.se-campaign-fab-time { font-size: 11px !important; font-weight: 700 !important; color: rgba(11,70,140,0.85) !important; font-variant-numeric: tabular-nums !important; }
@media (max-width: 768px) {
  #se-campaign-promo { margin: 20px auto 28px !important; padding: 0 12px !important; }
  .se-campaign-fab { left: 10px !important; top: 116px !important; }
  body.admin-bar .se-campaign-fab { top: 148px !important; }
}
</style>
<script>
${script}
(function () {
  var fab = document.querySelector('.se-campaign-fab');
  var builder = document.getElementById('membershipBuilder');
  if (fab && builder && 'IntersectionObserver' in window) {
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) fab.classList.add('is-hidden');
        else fab.classList.remove('is-hidden');
      });
    }, { threshold: 0.18, rootMargin: '-10% 0px -10% 0px' });
    io.observe(builder);
  }
})();
</script>`;
}

function renderBanner(manifest) {
  const img = manifest.heroImage || PARKED.heroImage;
  const primaryHref = manifest.primaryCta.href;
  const secondaryHref = manifest.secondaryCta.href;
  const primaryLabel = escapeHtml(manifest.primaryCta.label);
  const secondaryLabel = escapeHtml(manifest.secondaryCta.label);
  const perks = perkItems(manifest)
    .map((p) => `<li>${p}</li>`)
    .join('\n        ');
  const script = countdownScriptFromUnits(manifest, {
    'se-campaign-banner-days': 'd',
    'se-campaign-banner-hours': 'h',
    'se-campaign-banner-minutes': 'm',
    'se-campaign-banner-seconds': 's',
  });

  return `<!--
  HOMEPAGE CAMPAIGN BANNER — generated by scripts/campaign.
  Paste as ONE Custom HTML block on the homepage (Thrive).
  Links to: ${primaryHref}
-->
<style>
#se-campaign-banner,
#se-campaign-banner * {
  box-sizing: border-box !important;
  -webkit-font-smoothing: antialiased !important;
}
#se-campaign-banner {
  position: relative !important;
  isolation: isolate !important;
  overflow: hidden !important;
  border-radius: 24px !important;
  min-height: 420px !important;
  max-width: 1200px !important;
  width: 100% !important;
  margin: 32px auto !important;
  box-shadow: 0 28px 70px rgba(10, 22, 42, 0.22) !important;
  text-align: center !important;
  font-family: Montserrat, system-ui, sans-serif !important;
}
#se-campaign-banner .se-campaign-banner__bg {
  position: absolute !important;
  inset: 0 !important;
  z-index: 0 !important;
}
#se-campaign-banner .se-campaign-banner__bg img {
  width: 100% !important;
  height: 100% !important;
  object-fit: cover !important;
  display: block !important;
}
#se-campaign-banner .se-campaign-banner__overlay {
  position: absolute !important;
  inset: 0 !important;
  z-index: 1 !important;
  background:
    radial-gradient(circle at 50% 22%, rgba(61, 152, 255, 0.24), transparent 45%),
    linear-gradient(180deg, rgba(0, 16, 35, 0.22) 0%, rgba(0, 16, 35, 0.52) 62%, rgba(0, 16, 35, 0.68) 100%) !important;
}
#se-campaign-banner .se-campaign-banner__content {
  position: relative !important;
  z-index: 2 !important;
  display: flex !important;
  flex-direction: column !important;
  align-items: center !important;
  width: 100% !important;
  max-width: 820px !important;
  margin: 0 auto !important;
  padding: 72px 28px 62px !important;
}
#se-campaign-banner .se-campaign-banner__eyebrow {
  display: inline-block !important;
  margin: 0 0 14px !important;
  padding: 10px 24px !important;
  border-radius: 999px !important;
  color: #1a1205 !important;
  background: linear-gradient(135deg, #f0d78c, #b8860b) !important;
  font-size: 11px !important;
  font-weight: 800 !important;
  letter-spacing: 0.12em !important;
  text-transform: uppercase !important;
  max-width: 100% !important;
  overflow-wrap: break-word !important;
}
#se-campaign-banner .se-campaign-banner__title {
  margin: 0 0 16px !important;
  color: #ffffff !important;
  font-size: clamp(28px, 4vw, 44px) !important;
  font-weight: 800 !important;
  letter-spacing: -0.02em !important;
  line-height: 1.15 !important;
  text-wrap: balance !important;
  max-width: 100% !important;
  overflow-wrap: break-word !important;
}
#se-campaign-banner .se-campaign-banner__perks {
  display: flex !important;
  flex-wrap: wrap !important;
  justify-content: center !important;
  gap: 8px !important;
  margin: 0 0 16px !important;
  padding: 0 !important;
  list-style: none !important;
  width: 100% !important;
}
#se-campaign-banner .se-campaign-banner__perks li {
  display: inline-block !important;
  padding: 7px 12px !important;
  color: #fff !important;
  background: rgba(0,0,0,0.28) !important;
  border: 1px solid rgba(255,255,255,0.22) !important;
  border-radius: 999px !important;
  font-size: 12px !important;
  font-weight: 600 !important;
}
#se-campaign-banner .se-campaign-banner__perks strong { color: #ffd978 !important; }
#se-campaign-banner .se-campaign-banner__countdown {
  display: flex !important;
  justify-content: center !important;
  gap: 6px !important;
  margin: 0 0 20px !important;
  font-variant-numeric: tabular-nums !important;
}
#se-campaign-banner .se-campaign-banner__cd {
  min-width: 48px !important;
  padding: 7px 5px !important;
  background: rgba(0,0,0,0.3) !important;
  border: 1px solid rgba(255,255,255,0.16) !important;
  border-radius: 10px !important;
  color: #fff !important;
  font-size: 16px !important;
  font-weight: 800 !important;
}
#se-campaign-banner .se-campaign-banner__cd small {
  display: block !important;
  margin-top: 2px !important;
  font-size: 9px !important;
  font-weight: 700 !important;
  letter-spacing: 0.08em !important;
  text-transform: uppercase !important;
  color: rgba(255,255,255,0.7) !important;
}
#se-campaign-banner .se-campaign-banner__actions {
  display: flex !important;
  flex-wrap: wrap !important;
  justify-content: center !important;
  gap: 10px !important;
  width: 100% !important;
  padding-inline: clamp(1rem, 4vw, 2rem) !important;
}
#se-campaign-banner .se-campaign-banner__btn {
  display: inline-flex !important;
  align-items: center !important;
  justify-content: center !important;
  min-height: 44px !important;
  padding: 12px 26px !important;
  border-radius: 999px !important;
  font-size: 14px !important;
  font-weight: 800 !important;
  letter-spacing: 0.04em !important;
  text-transform: uppercase !important;
  text-decoration: none !important;
  max-width: min(280px, calc(100vw - 64px)) !important;
}
#se-campaign-banner .se-campaign-banner__btn-primary {
  color: #1a1205 !important;
  background: linear-gradient(135deg, #f0d78c, #b8860b) !important;
  box-shadow: 0 8px 22px rgba(184,134,11,0.45) !important;
}
#se-campaign-banner .se-campaign-banner__btn-secondary {
  color: #ffffff !important;
  background: transparent !important;
  border: 2px solid rgba(255,255,255,0.85) !important;
}
@media (max-width: 640px) {
  #se-campaign-banner .se-campaign-banner__content { padding: 48px 16px 40px !important; }
  #se-campaign-banner { min-height: 360px !important; border-radius: 18px !important; margin: 20px auto !important; }
  #se-campaign-banner .se-campaign-banner__actions { flex-direction: column !important; align-items: center !important; }
  #se-campaign-banner .se-campaign-banner__btn { width: 100% !important; max-width: min(280px, calc(100vw - 64px)) !important; }
}
</style>
<section class="se-campaign-banner" id="se-campaign-banner" role="region" aria-label="${escapeHtml(manifest.eyebrow || 'Membership special')}">
  <div class="se-campaign-banner__bg">
    <img src="${escapeHtml(img.src)}" alt="${escapeHtml(img.alt || '')}" loading="lazy">
  </div>
  <div class="se-campaign-banner__overlay"></div>
  <div class="se-campaign-banner__content">
    <span class="se-campaign-banner__eyebrow">${escapeHtml(manifest.eyebrow || 'Special offer')}</span>
    <h2 class="se-campaign-banner__title">${headlineHtml(manifest.headline)}</h2>
    <ul class="se-campaign-banner__perks">
        ${perks}
    </ul>
    <div class="se-campaign-banner__countdown" aria-live="polite">
      <div class="se-campaign-banner__cd"><span id="se-campaign-banner-days">00</span><small>d</small></div>
      <div class="se-campaign-banner__cd"><span id="se-campaign-banner-hours">00</span><small>h</small></div>
      <div class="se-campaign-banner__cd"><span id="se-campaign-banner-minutes">00</span><small>m</small></div>
      <div class="se-campaign-banner__cd"><span id="se-campaign-banner-seconds">00</span><small>s</small></div>
    </div>
    <div class="se-campaign-banner__actions">
      <a class="se-campaign-banner__btn se-campaign-banner__btn-primary" href="${escapeHtml(primaryHref)}">${primaryLabel}</a>
      <a class="se-campaign-banner__btn se-campaign-banner__btn-secondary" href="${escapeHtml(secondaryHref)}">${secondaryLabel}</a>
    </div>
  </div>
</section>
<script>
${script}
</script>
`;
}

function campaignHref(manifest) {
  const base = 'https://southendclub.com/special-offer/';
  if (manifest.status === 'parked' || !manifest.offerTag || manifest.offerTag.startsWith('UNSET')) {
    return base;
  }
  return `${base}?utm_campaign=${encodeURIComponent(manifest.offerTag)}`;
}

function renderButton(manifest) {
  const href = campaignHref(manifest);
  const label = manifest.status === 'parked'
    ? 'OFFER NOT SET'
    : (manifest.enrollment ? `$${manifest.enrollment} Offer` : (manifest.primaryCta.label || 'Offer'));
  const aria = escapeHtml(manifest.eyebrow || 'Special offer');
  const t = toneOf(manifest);
  const endJs = endExpr(manifest);

  return `<!--
  GLOBAL SPECIAL OFFER BUTTON
  Site-wide WPCode HTML snippet, footer insert.
  Coexists with #se-bk-floating-wrap (bottom-left tour, desktop) and #se-crm-btn (bottom-right message).
  Hides on /special-offer/ and after campaign expiry.
-->
<style>
#se-campaign-float,
#se-campaign-float * {
  box-sizing: border-box !important;
  -webkit-font-smoothing: antialiased !important;
}
#se-campaign-float {
  display: none;
  position: fixed;
  left: 24px;
  bottom: calc(96px + env(safe-area-inset-bottom, 0px));
  z-index: 2147483645;
  align-items: center;
  gap: 8px;
  min-height: 44px;
  max-width: min(220px, calc(100vw - 48px));
  padding: 10px 14px;
  border-radius: 999px;
  text-decoration: none;
  color: #1a1205;
  background: linear-gradient(135deg, #f0d78c, #b8860b);
  box-shadow: 0 8px 24px rgba(184,134,11,0.35);
  font-family: Montserrat, system-ui, sans-serif;
  font-weight: 800;
  font-size: 13px;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  overflow-wrap: break-word;
}
#se-campaign-float.is-visible { display: inline-flex; }
#se-campaign-float:focus-visible {
  outline: 2px solid #0b468c;
  outline-offset: 3px;
}
@media (max-width: 1023px) {
  #se-campaign-float {
    left: 16px;
    bottom: calc(24px + env(safe-area-inset-bottom, 0px));
  }
}
@media (max-width: 320px) {
  #se-campaign-float {
    left: 12px;
    padding: 10px 12px;
    font-size: 12px;
    max-width: calc(100vw - 24px);
  }
}
</style>
<a id="se-campaign-float" href="${escapeHtml(href)}" aria-label="${aria}">
  <span aria-hidden="true">${t.fabEmoji}</span>
  <span>${escapeHtml(label)}</span>
</a>
<script>
(function () {
  var END = ${endJs};
  var el = document.getElementById('se-campaign-float');
  if (!el) return;
  var path = (location.pathname || '').replace(/\\/+$/, '');
  if (/\\/special-offer$/i.test(path)) return;
  if (!END) return;
  if (new Date() >= END) return;
  el.classList.add('is-visible');
})();
</script>
`;
}

function renderBuilderJs(manifest) {
  const tmplPath = path.join(__dirname, 'templates', 'membership-builder.js.tmpl');
  let tmpl = fs.readFileSync(tmplPath, 'utf8').replace(/^\uFEFF/, '');
  const header = manifest.status === 'parked'
    ? ' * Offer: NOT SET. Set enrollment, wording, countdown and the offer: tag before launch.'
    : ` * Offer: $${manifest.enrollment} enrollment`
      + (hasDuesDiscount(manifest)
        ? ` + $${duesMap(manifest).single}/$${duesMap(manifest).couple}/$${duesMap(manifest).family} off dues`
        : '')
      + (manifest.guestPasses ? ` + ${manifest.guestPasses} guest passes` : '')
      + (manifest.endLabel ? ` through ${manifest.endLabel}` : '')
      + '.';
  tmpl = tmpl.split('{{OFFER_HEADER}}').join(header);
  tmpl = tmpl.split('{{SPECIAL_ENROLLMENT}}').join(String(manifest.enrollment));
  tmpl = tmpl.split('{{DUES_DISCOUNTS_JSON}}').join(JSON.stringify(duesMap(manifest)));
  tmpl = tmpl.split('{{LIMITED_TIME_JSON}}').join(JSON.stringify(manifest.limitedTimeText));
  tmpl = tmpl.split('{{OFFER_TAG_JSON}}').join(JSON.stringify(manifest.offerTag));
  if (tmpl.includes('{{')) {
    throw new Error('Unreplaced builder template placeholder');
  }
  return tmpl.replace(/\r\n/g, '\n');
}

function renderBuilderElement(manifest) {
  const js = renderBuilderJs(manifest);
  return `<!-- Special-offer pricing (inlined — do not rely on WPCode 7966 for this page) -->
<script>
${js}
</script>`;
}

function renderPreview(manifest) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Campaign preview — ${escapeHtml(manifest.id)}</title>
  <style>body{margin:0;background:#f8f2e1;font-family:Montserrat,system-ui,sans-serif}</style>
</head>
<body>
${renderBanner(manifest)}
${renderPromo(manifest)}
${renderButton(manifest)}
</body>
</html>
`;
}

function renderYoast(manifest) {
  return `# Yoast metadata — ${manifest.id}

Editing meta tags in the Thrive page HTML does **not** affect Google.
Paste these into the Yoast panel for \`/special-offer/\`.

## Title

\`\`\`
${(manifest.yoast && manifest.yoast.title) || ''}
\`\`\`

## Meta description

\`\`\`
${(manifest.yoast && manifest.yoast.description) || ''}
\`\`\`
`;
}

module.exports = {
  TONES,
  renderMeta,
  renderCallout,
  renderPromo,
  renderBanner,
  renderButton,
  renderBuilderJs,
  renderBuilderElement,
  renderPreview,
  renderYoast,
  campaignHref,
  countdownScriptFromUnits,
};
