/*
 * Builds every generated tour-confirmation artifact from the page source
 * (single source of truth: Tour Confirmation HTML.html + CSS.css).
 *
 *   node patches/tour-confirmation-paste/generate.js      # write artifacts
 *
 * `guard:tour-confirmation` (scripts/audit/tour-confirmation-guard.js)
 * requires this module and recomputes everything, so an artifact edited
 * by hand — or a source edited without regenerating — fails `npm run
 * guard` deterministically. Editing the artifacts directly is therefore
 * not just discouraged in a README; it is mechanically caught.
 *
 * History that shaped this (2026-08-20): Thrive Custom HTML pastes
 * truncated at ~32KB, and WordPress post content entity-encodes stray
 * ampersands on output (&& becomes &#038;&#038;) which breaks inline JS
 * — so the page's JS lives in WPCode snippet 9998 and the split below
 * exists at all.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const PAGE_DIR = path.join(ROOT, 'Website', 'Pages', 'Tours (Category)', 'tour-confirmation');
const HTML_SOURCE = path.join(PAGE_DIR, 'Tour Confirmation HTML.html');
const CSS_SOURCE = path.join(PAGE_DIR, 'Tour Confirmation CSS.css');
const OUT_DIR = __dirname;
const THRIVE_CAP = 32 * 1024;

function build() {
  const html = fs.readFileSync(HTML_SOURCE, 'utf8').replace(/\r\n/g, '\n');
  const css = fs.readFileSync(CSS_SOURCE, 'utf8').replace(/\r\n/g, '\n').trim();

  const splitAt = html.indexOf('<script>');
  if (splitAt === -1) throw new Error('No <script> found in page source.');

  const markup = html.slice(0, splitAt).replace(/\s+$/, '') + '\n';
  const scripts = html.slice(splitAt);

  if (!/<\/div>\s*$/.test(markup)) throw new Error('Markup does not end with </div> — split boundary moved?');

  const blocks = [...scripts.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1].trim());
  if (blocks.length < 3) throw new Error('Expected 3 script blocks, found ' + blocks.length);
  blocks.forEach(b => { new Function(b); }); // throws on syntax error

  // WPCode 9998 body: each IIFE gains a page guard so the site-wide
  // footer snippet no-ops everywhere except the tour-confirmation page.
  const guarded = blocks.map(b => b.replace(/('use strict';)/, "$1\n  if (!document.getElementById('se-tc-page')) return;"));
  guarded.forEach((g, i) => {
    if (g.indexOf("getElementById('se-tc-page')") === -1) throw new Error('block ' + i + ' did not take the page guard');
    new Function(g);
  });
  const wpcodeJs = "/* Tour-confirmation page JS — WPCode snippet 9998 (site-wide footer, guarded).\n" +
    " * GENERATED from the script blocks in\n" +
    " * Website/Pages/Tours (Category)/tour-confirmation/Tour Confirmation HTML.html\n" +
    " * by patches/tour-confirmation-paste/generate.js — edit the page source, then\n" +
    " * regenerate and re-paste; guard:tour-confirmation fails on drift.\n" +
    " * WHY WPCode and not inline: WordPress content filters entity-encode\n" +
    " * stray ampersands in post content on output (&& becomes &#038;&#038;),\n" +
    " * which is a syntax error. WPCode injects raw. Discovered 2026-08-20.\n" +
    " * Each IIFE no-ops unless #se-tc-page exists on the page. */\n\n" + guarded.join('\n\n');

  const header1 = '<!-- Thrive paste 1/2: PAGE MARKUP for /tour-confirmation/. Regenerated by patches/tour-confirmation-paste/generate.js — edit the page source, not this file. Paste 2/2 (scripts) goes in a SEPARATE Custom HTML element below this one: one element cannot hold both (32KB Thrive cap). -->\n';
  const header2 = '<!-- Thrive paste 2/2: PAGE SCRIPTS for /tour-confirmation/. Regenerated by patches/tour-confirmation-paste/generate.js — edit the page source, not this file. Must sit in its own Custom HTML element BELOW the markup element. -->\n';

  const gutenberg = '<!-- wp:html -->\n' + markup.trim() + '\n<!-- /wp:html -->\n\n<!-- wp:html -->\n<style>\n' + css + '\n</style>\n<!-- /wp:html -->\n';

  // Footer member-reviews rotator (handoffs/footer-reviews-rotator.md):
  // quotes come from the tour page's slides; rotator CSS + JS come from
  // the canonical component file. Delivered as WPCode HTML snippet
  // auto-inserted site-wide footer; a relocation script moves it above
  // the footer's promo CTA (.sec-footer-cta) and only reveals it there.
  const COMPONENT = path.join(ROOT, 'Website', 'Components', 'quote-rotator', 'quote-rotator.html');
  const comp = fs.readFileSync(COMPONENT, 'utf8').replace(/\r\n/g, '\n');
  const compStyle = (comp.match(/<style>([\s\S]*?)<\/style>/) || [])[1];
  const compScript = (comp.match(/<script>([\s\S]*?)<\/script>/) || [])[1];
  if (!compStyle || !compScript) throw new Error('component style/script not found');
  new Function(compScript);

  const slides = markup.match(/<blockquote class="se-qr-slide"[\s\S]*?<\/blockquote>/g) || [];
  if (slides.length < 10) throw new Error('expected the tour page slide list, found ' + slides.length);
  const footerSlides = slides.map(s => s.replace(/ data-interests="[^"]*"/, '')).join('\n        ');

  const footerElement = [
    '<!-- Footer member-reviews rotator — GENERATED by patches/tour-confirmation-paste/generate.js.',
    '     Quotes come from the tour-confirmation page source; rotator CSS/JS from',
    '     Website/Components/quote-rotator/. Edit those sources, regenerate, re-paste',
    '     WPCode snippet (see live/wpcode/ mirror) — guard:tour-confirmation fails on drift. -->',
    '<style>' + compStyle.trimEnd(),
    '',
    '/* ── DARK-FOOTER ARMOR — the Thrive footer symbol styles blockquote as a',
    '   big near-white card and out-ranks class selectors (same failure class',
    '   as the #tve_editor armor on the tour page). Every declaration the theme',
    '   can paint is therefore re-asserted under the #se-footer-reviews id',
    '   with !important, with NO variable reliance. ── */',
    '#se-footer-reviews { display: none; padding: 38px 20px 40px; }',
    '#se-footer-reviews .se-fr-title {',
    '  text-align: center !important; font-family: Montserrat, system-ui, sans-serif !important;',
    '  font-size: 13px !important; font-weight: 700 !important; letter-spacing: 0.14em !important; text-transform: uppercase !important;',
    '  color: #f6b01e !important; -webkit-text-fill-color: #f6b01e !important; margin: 0 0 6px !important;',
    '}',
    '#se-footer-reviews .se-fr-rule { width: 44px; height: 2px; background: #f6b01e; opacity: 0.7; margin: 0 auto 22px; border-radius: 1px; }',
    '',
    '/* Rotator geometry */',
    '#se-footer-reviews .se-qr { position: relative !important; max-width: 720px !important; margin: 0 auto !important; }',
    '#se-footer-reviews .se-qr-track { position: relative !important; }',
    '',
    '/* Slide card — kills the theme blockquote white card */',
    '#se-footer-reviews .se-qr-slide {',
    '  background: rgba(255, 255, 255, 0.07) !important;',
    '  border: 2px solid rgba(255, 255, 255, 0.18) !important;',
    '  border-radius: 14px !important;',
    '  padding: 28px 30px 22px !important;',
    '  margin: 0 !important;',
    '  text-align: center !important;',
    '  box-shadow: none !important;',
    '}',
    '#se-footer-reviews .se-qr-slide::before,',
    '#se-footer-reviews .se-qr-slide::after { content: none !important; }',
    '',
    '/* Text */',
    '#se-footer-reviews .se-qr-slide p {',
    '  font-family: Montserrat, system-ui, sans-serif !important;',
    '  font-size: 15px !important; line-height: 1.75 !important; font-style: italic !important;',
    '  margin: 0 0 16px !important;',
    '  color: rgba(255, 255, 255, 0.88) !important; -webkit-text-fill-color: rgba(255, 255, 255, 0.88) !important;',
    '}',
    '#se-footer-reviews .se-qr-slide p.se-qr-stars {',
    '  font-style: normal !important; letter-spacing: 3px !important; font-size: 15px !important; margin: 0 0 12px !important;',
    '  color: #f6b01e !important; -webkit-text-fill-color: #f6b01e !important;',
    '}',
    '#se-footer-reviews .se-qr-slide footer {',
    '  font-family: Montserrat, system-ui, sans-serif !important;',
    '  font-size: 13px !important; font-weight: 700 !important; font-style: normal !important;',
    '  color: #ffffff !important; -webkit-text-fill-color: #ffffff !important;',
    '}',
    '#se-footer-reviews .se-qr-slide footer span {',
    '  display: block !important; margin-top: 3px !important; font-weight: 500 !important; font-size: 11.5px !important;',
    '  color: rgba(255, 255, 255, 0.65) !important; -webkit-text-fill-color: rgba(255, 255, 255, 0.65) !important; opacity: 1 !important;',
    '}',
    '#se-footer-reviews .se-qr-name-link {',
    '  color: #ffffff !important; -webkit-text-fill-color: #ffffff !important;',
    '  text-decoration: none !important; border-bottom: 1px dotted rgba(255, 255, 255, 0.4) !important;',
    '}',
    '#se-footer-reviews .se-qr-name-link:hover { color: #f6b01e !important; -webkit-text-fill-color: #f6b01e !important; border-bottom: 1px solid #f6b01e !important; }',
    '',
    '/* Ready-state stacking mechanic, re-asserted under the id */',
    '#se-footer-reviews .se-qr.se-qr-ready .se-qr-track { display: grid !important; }',
    '#se-footer-reviews .se-qr.se-qr-ready .se-qr-slide {',
    '  grid-area: 1 / 1 !important;',
    '  opacity: 0 !important;',
    '  transform: translateY(14px) !important;',
    '  transition: opacity 0.6s ease, transform 0.6s ease, visibility 0.6s !important;',
    '  pointer-events: none !important;',
    '  visibility: hidden !important;',
    '}',
    '#se-footer-reviews .se-qr.se-qr-ready .se-qr-slide.se-qr-active {',
    '  opacity: 1 !important;',
    '  transform: translateY(0) !important;',
    '  pointer-events: auto !important;',
    '  visibility: visible !important;',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  #se-footer-reviews .se-qr.se-qr-ready .se-qr-slide { transition: none !important; transform: none !important; }',
    '}',
    '',
    '/* Arrows */',
    '#se-footer-reviews .se-qr-arrow {',
    '  position: absolute !important; top: 50% !important; transform: translateY(-50%) !important;',
    '  width: 38px !important; height: 38px !important; padding: 0 !important;',
    '  align-items: center !important; justify-content: center !important;',
    '  background: transparent !important; border: 2px solid rgba(255, 255, 255, 0.25) !important; border-radius: 50% !important;',
    '  color: #f6b01e !important; -webkit-text-fill-color: #f6b01e !important;',
    '  font-size: 16px !important; line-height: 1 !important; cursor: pointer !important; box-shadow: none !important; z-index: 2 !important;',
    '}',
    '#se-footer-reviews .se-qr-arrow:hover { border-color: #f6b01e !important; box-shadow: none !important; }',
    '#se-footer-reviews .se-qr.se-qr-ready .se-qr-arrow { display: inline-flex !important; }',
    '@media (max-width: 900px) {',
    '  #se-footer-reviews .se-qr.se-qr-ready .se-qr-arrow { display: none !important; }',
    '}',
    '',
    '/* Dots */',
    '#se-footer-reviews .se-qr.se-qr-ready .se-qr-dots { display: flex !important; justify-content: center !important; gap: 8px !important; margin-top: 18px !important; }',
    '#se-footer-reviews .se-qr-dot {',
    '  width: 9px !important; height: 9px !important; padding: 0 !important;',
    '  border: none !important; border-radius: 50% !important;',
    '  background: rgba(255, 255, 255, 0.25) !important; cursor: pointer !important;',
    '  transition: background 0.25s ease, transform 0.25s ease !important;',
    '}',
    '#se-footer-reviews .se-qr-dot.se-qr-dot-active { background: #f6b01e !important; transform: scale(1.25) !important; }',
    '</style>',
    '',
    '<div id="se-footer-reviews">',
    '  <p class="se-fr-title">&#9733; Member Reviews</p>',
    '  <div class="se-fr-rule"></div>',
    '  <div class="se-qr se-qr-footer" data-interval="7000" role="region" aria-label="Member reviews">',
    '    <button type="button" class="se-qr-arrow se-qr-prev" aria-label="Previous quote">&#8249;</button>',
    '    <button type="button" class="se-qr-arrow se-qr-next" aria-label="Next quote">&#8250;</button>',
    '    <div class="se-qr-track">',
    '        ' + footerSlides,
    '    </div>',
    '    <div class="se-qr-dots" role="tablist" aria-label="Choose quote"></div>',
    '  </div>',
    '</div>',
    '',
    '<script>',
    "/* Relocate the block from the end of <body> (where WPCode footer",
    "   insertion lands) to just above the footer's promo CTA, then reveal",
    "   it. If the anchor is ever missing, the block stays hidden — never",
    "   a dangling widget at the page bottom. */",
    '(function(){',
    "  'use strict';",
    "  var el = document.getElementById('se-footer-reviews');",
    '  if (!el) return;',
    "  var cta = document.querySelector('.sec-footer-cta');",
    '  if (!cta || !cta.parentNode) return;',
    '  cta.parentNode.insertBefore(el, cta);',
    "  el.style.display = 'block';",
    '})();',
    '</script>',
    '',
    '<script>' + compScript.trimEnd(),
    '</script>',
    '',
  ].join('\n');

  return {
    'element-1-markup.html': header1 + markup,
    'element-2-scripts.html': header2 + scripts,
    'gutenberg-content.html': gutenberg,
    'wpcode-tour-confirmation.js': wpcodeJs,
    'footer-reviews-element.html': footerElement,
  };
}

module.exports = { build, OUT_DIR, THRIVE_CAP };

if (require.main === module) {
  const artifacts = build();
  for (const [name, content] of Object.entries(artifacts)) {
    const bytes = Buffer.byteLength(content, 'utf8');
    if (name.startsWith('element-') && bytes > THRIVE_CAP - 2048) {
      throw new Error(name + ' is ' + bytes + ' bytes — too close to the 32KB Thrive cap.');
    }
    fs.writeFileSync(path.join(OUT_DIR, name), content);
    console.log(name + ': ' + bytes + ' bytes');
  }
  console.log('all artifacts written; script blocks compile');
}
