/*
 * Regenerates the two paste-ready Thrive artifacts for /tour-confirmation/
 * from the page source. Run after ANY edit to the page HTML:
 *
 *   node patches/tour-confirmation-paste/generate.js
 *
 * Why two elements: Thrive's Custom HTML element silently truncates its
 * content at ~32KB (discovered 2026-08-20 — two pastes in a row lost
 * their tail at the same total offset, killing all page JS). The page
 * splits at the markup/script boundary; each half sits well under the
 * cap. Element 1 holds everything through the closing </div> of
 * #se-tc-page; element 2 holds the three <script> blocks.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const SOURCE = path.join(ROOT, 'Website', 'Pages', 'Tours (Category)', 'tour-confirmation', 'Tour Confirmation HTML.html');
const OUT_DIR = __dirname;
const CAP = 32 * 1024;

const html = fs.readFileSync(SOURCE, 'utf8');

const splitAt = html.indexOf('<script>');
if (splitAt === -1) throw new Error('No <script> found in page source.');

const markup = html.slice(0, splitAt).replace(/\s+$/, '') + '\n';
const scripts = html.slice(splitAt);

// Sanity: element 1 must end with the page root's closing tag.
if (!/<\/div>\s*$/.test(markup)) throw new Error('Element 1 does not end with </div> — split boundary moved?');

// Sanity: every script block in element 2 must compile.
const blocks = [...scripts.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]);
if (blocks.length < 3) throw new Error('Expected 3 script blocks, found ' + blocks.length);
blocks.forEach((b, i) => { new Function(b); }); // throws on syntax error

const header1 = '<!-- Thrive paste 1/2: PAGE MARKUP for /tour-confirmation/. Regenerated by patches/tour-confirmation-paste/generate.js — edit the page source, not this file. Paste 2/2 (scripts) goes in a SEPARATE Custom HTML element below this one: one element cannot hold both (32KB Thrive cap). -->\n';
const header2 = '<!-- Thrive paste 2/2: PAGE SCRIPTS for /tour-confirmation/. Regenerated by patches/tour-confirmation-paste/generate.js — edit the page source, not this file. Must sit in its own Custom HTML element BELOW the markup element. -->\n';

const out1 = header1 + markup;
const out2 = header2 + scripts;

for (const [name, content] of [['element-1-markup.html', out1], ['element-2-scripts.html', out2]]) {
  const bytes = Buffer.byteLength(content, 'utf8');
  if (bytes > CAP - 2048) throw new Error(name + ' is ' + bytes + ' bytes — too close to the 32KB Thrive cap.');
  fs.writeFileSync(path.join(OUT_DIR, name), content);
  console.log(name + ': ' + bytes + ' bytes (cap ' + CAP + ')');
}
console.log('script blocks: ' + blocks.length + ', all compile');
