/*
 * Builds every generated tour-confirmation artifact from the page source
 * (single source of truth: Tour Confirmation HTML.html + CSS.css).
 *
 *   node patches/tour-confirmation-paste/generate.js      # write artifacts
 *
 * `guard:tour-confirmation` (scripts/audit/tour-confirmation-guard.js)
 * requires this module and recomputes everything, so an artifact edited
 * by hand — or a source edited without regenerating — fails `npm run
 * guard` deterministically. Editing the artifacts directly is therefore
 * not just discouraged in a README; it is mechanically caught.
 *
 * History that shaped this (2026-08-20): Thrive Custom HTML pastes
 * truncated at ~32KB, and WordPress post content entity-encodes stray
 * ampersands on output (&& becomes &#038;&#038;) which breaks inline JS
 * — so the page's JS lives in WPCode snippet 9998 and the split below
 * exists at all.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const PAGE_DIR = path.join(ROOT, 'Website', 'Pages', 'Tours (Category)', 'tour-confirmation');
const HTML_SOURCE = path.join(PAGE_DIR, 'Tour Confirmation HTML.html');
const CSS_SOURCE = path.join(PAGE_DIR, 'Tour Confirmation CSS.css');
const OUT_DIR = __dirname;
const THRIVE_CAP = 32 * 1024;

function build() {
  const html = fs.readFileSync(HTML_SOURCE, 'utf8').replace(/\r\n/g, '\n');
  const css = fs.readFileSync(CSS_SOURCE, 'utf8').replace(/\r\n/g, '\n').trim();

  const splitAt = html.indexOf('<script>');
  if (splitAt === -1) throw new Error('No <script> found in page source.');

  const markup = html.slice(0, splitAt).replace(/\s+$/, '') + '\n';
  const scripts = html.slice(splitAt);

  if (!/<\/div>\s*$/.test(markup)) throw new Error('Markup does not end with </div> — split boundary moved?');

  const blocks = [...scripts.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1].trim());
  if (blocks.length < 3) throw new Error('Expected 3 script blocks, found ' + blocks.length);
  blocks.forEach(b => { new Function(b); }); // throws on syntax error

  // WPCode 9998 body: each IIFE gains a page guard so the site-wide
  // footer snippet no-ops everywhere except the tour-confirmation page.
  const guarded = blocks.map(b => b.replace(/('use strict';)/, "$1\n  if (!document.getElementById('se-tc-page')) return;"));
  guarded.forEach((g, i) => {
    if (g.indexOf("getElementById('se-tc-page')") === -1) throw new Error('block ' + i + ' did not take the page guard');
    new Function(g);
  });
  const wpcodeJs = "/* Tour-confirmation page JS — WPCode snippet 9998 (site-wide footer, guarded).\n" +
    " * GENERATED from the script blocks in\n" +
    " * Website/Pages/Tours (Category)/tour-confirmation/Tour Confirmation HTML.html\n" +
    " * by patches/tour-confirmation-paste/generate.js — edit the page source, then\n" +
    " * regenerate and re-paste; guard:tour-confirmation fails on drift.\n" +
    " * WHY WPCode and not inline: WordPress content filters entity-encode\n" +
    " * stray ampersands in post content on output (&& becomes &#038;&#038;),\n" +
    " * which is a syntax error. WPCode injects raw. Discovered 2026-08-20.\n" +
    " * Each IIFE no-ops unless #se-tc-page exists on the page. */\n\n" + guarded.join('\n\n');

  const header1 = '<!-- Thrive paste 1/2: PAGE MARKUP for /tour-confirmation/. Regenerated by patches/tour-confirmation-paste/generate.js — edit the page source, not this file. Paste 2/2 (scripts) goes in a SEPARATE Custom HTML element below this one: one element cannot hold both (32KB Thrive cap). -->\n';
  const header2 = '<!-- Thrive paste 2/2: PAGE SCRIPTS for /tour-confirmation/. Regenerated by patches/tour-confirmation-paste/generate.js — edit the page source, not this file. Must sit in its own Custom HTML element BELOW the markup element. -->\n';

  const gutenberg = '<!-- wp:html -->\n' + markup.trim() + '\n<!-- /wp:html -->\n\n<!-- wp:html -->\n<style>\n' + css + '\n</style>\n<!-- /wp:html -->\n';

  return {
    'element-1-markup.html': header1 + markup,
    'element-2-scripts.html': header2 + scripts,
    'gutenberg-content.html': gutenberg,
    'wpcode-tour-confirmation.js': wpcodeJs,
  };
}

module.exports = { build, OUT_DIR, THRIVE_CAP };

if (require.main === module) {
  const artifacts = build();
  for (const [name, content] of Object.entries(artifacts)) {
    const bytes = Buffer.byteLength(content, 'utf8');
    if (name.startsWith('element-') && bytes > THRIVE_CAP - 2048) {
      throw new Error(name + ' is ' + bytes + ' bytes — too close to the 32KB Thrive cap.');
    }
    fs.writeFileSync(path.join(OUT_DIR, name), content);
    console.log(name + ': ' + bytes + ' bytes');
  }
  console.log('all artifacts written; script blocks compile');
}
